//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab09.Database_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANET()
        {
            this.SATELLITES = new HashSet<SATELLITE>();
        }
    
        public string Name { get; set; }
        public int Radius { get; set; }
        public decimal Core_Temperature { get; set; }
        public bool Have_Atmosphere { get; set; }
        public bool Have_Life { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATELLITE> SATELLITES { get; set; }
    }
}
