//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab09.Database_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATELLITE
    {
        public string Name { get; set; }
        public string Planet_Name { get; set; }
        public int Radius { get; set; }
        public int Planetary_Distance { get; set; }
        public string Image { get; set; }
    
        public virtual PLANET PLANET { get; set; }
    }
}
