USE [Lab11]
GO

/****** Object:  Table [dbo].[Student]    Script Date: 14/04/2023 23:00:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Student](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Course] [int] NOT NULL,
 CONSTRAINT [PK__Student__3214EC078A8825A1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Student]  WITH CHECK ADD  CONSTRAINT [FK__Student__Course__267ABA7A] FOREIGN KEY([Course])
REFERENCES [dbo].[Course] ([Id])
GO

ALTER TABLE [dbo].[Student] CHECK CONSTRAINT [FK__Student__Course__267ABA7A]
GO


